algoritmo "semnome"
// Função :
// Autor :
// Data : 06/09/2025
// Seção de Declarações 
var
a, b, c, delta, raiz1, raiz2 : real
inicio
escreva("Digite o valor de a: ")
       leia(a)
       escreva("Digite o valor de b: ")
       leia(b)
       escreva("Digite o valor de c: ")
       leia(c)
       
       delta <- b*b - 4*a*c
  escreva("Delta é ", delta:2:2)
fimalgoritmo




