algoritmo "semnome"
// Função : Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!
// Autor :
// Data : 18/09/2025
// Seção de Declarações 
var
v, c: inteiro
inicio
escreva("Digite um valor: ")
leia(v)
c <- 0
enquanto (c < v) faca
  c <- c + 1
  escreva(c)
fimenquanto
escreva(" Acabou!!!")
fimalgoritmo
