algoritmo "semnome"
// Função : Faça um programa que leia 7 números inteiros e no final mostre o somatório
//entre eles.
// Autor :
// Data : 19/09/2025
// Seção de Declarações 
var
c, v, tot: inteiro
inicio
c <- 0
v <- 1
enquanto (c < 7) faca
     c <- c + 1
escreval("Digite o ", c,"º valor: ")
leia(v)
    tot <- tot + v
fimenquanto
escreva("A soma dos numeros é ", tot)
fimalgoritmo
