algoritmo "semnome"
// Função : Crie um programa que tenha um procedimento Gerador() que, quando chamado,
// mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
// Ex: Ao chamar Gerador() aparece:
//+-------=======------+
// Olá, Mundo!
//+-------=======------+

var

procedimento gerador()
inicio
      escreval("+-------=====-------+")
      escreval("Olá Mundo!!!")
      escreval("+-------=====-------+")

fimprocedimento
inicio
gerador()
fimalgoritmo
