algoritmo "semnome"
// Função :
// Autor :
// Data : 03/08/2025
// Seção de Declarações 
var
     cafe: inteiro
inicio
// Seção de Comandos 
   escreva("Qual tipo de café?")
   escreva("Digite [1] para café curto")
   escreva("DIgite [2] para café longo")
   escreva("Digite [3] para café normal")
   leia(cafe)
     escolha cafe
       caso 1

     
     
     fimescolha

fimalgoritmo
