algoritmo "ler numero e somar "
// Função : solicititar um numro 5 vezes e somalos
// Autor :
// Data : 05/07/2025
// Seção de Declarações 
var
cont, n, res: inteiro
inicio
// Seção de Comandos
   cont <- 1
   res <- 0
   enquanto (cont <= 5) faca

      escreva ("Digite o", cont,"º numero: ")
      leia (n)
      res <- res + n
      cont <- cont + 1
   fimenquanto
   
   escreva ("A soma dos valores é",res)
fimalgoritmo
