Algoritmo "Operadores relacionais"
//  
//  
// 
//  
// Descrição   :
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/06/2025
Var
// Seção de Declarações das variáveis
// valores inteiro ou reais
a, b, c: inteiro

Inicio
// operadores

  a <- 2
  b <- 3
  c <- 5
  
  escreval(a<>b)
  escreval(b<c)
  escreval(a>2)
  escreval(a<=2)
  escreval(a=c+b)
  escreval(c>=b^a)
  escreval(c<=C%2)
  escreva(1=c%2)



Fimalgoritmo