Algoritmo "Operadores logicos"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/06/2025
Var
// Seção de Declarações das variáveis 
a, b, c: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   a <- 2
   b <- 3
   c <- 5
   escreval(verdadeiro e falso)
   escreval((a=b) ou (c>a))
   
   // o não inverte o resultado
   escreval(não((a=b) ou (c>a)))
Fimalgoritmo