algoritmo "par ou impa procedimentos"
// Função :
// Autor :
// Data : 12/07/2025
// Seção de Declarações 
var
a,b: inteiro
procedimento parimpar(b: inteiro)
inicio
             se(b%2=0)entao
               escreval("Par")
             senao
               escreva("Impar")
             fimse
fimprocedimento
inicio
     escreval("Digite o 1º numero: ")
     leia(a)
    parimpar(a)

fimalgoritmo
