algoritmo "semnome"
// Função :
// Autor :
// Data : 21/08/2025
// Seção de Declarações 
var
   x, y: inteiro
Procedimento soma (var a, b: inteiro)
inicio
// Seção de Comandos 
   a <- a + 1
   b <- b + 2
   escreval("Valor de A = " , a)
   escreval("Valor de B = ", b)
   escreval("Soma A + B = ", A+B)
fimprocedimento
inicio
   x <- 4
   y <- 8
   soma (x, y)
   escreval("Valor de X = ", x)
   escreval("Valor de Y = ", y)
   
fimalgoritmo
