algoritmo "semnome"
// Função :
// Autor :
// Data : 21/08/2025
// Seção de Declarações
var
  n1, n2: inteiro
  
procedimento soma(a, b: inteiro)
inicio

    escreva("A soma de",a, " +", b, " é igual a", a+b,".")

fimprocedimento
inicio
// Seção de Comandos 
   escreva("Digite o primeiro numero: ")
   leia(n1)
   escreva("Digite o segundo numero:  ")
   leia(n2)
   soma(n1, n2)
fimalgoritmo
